# This provides integration into the travis-ci.org CI system. For a overview
# check http://about.travis-ci.org/docs/user/getting-started/
#
# Some notes:
# - language is "C" because the travis chroot for python installs a non-repo
#   python3.3 from a PPA
sudo: required
dist: trusty
language: c
before_install:
- sudo apt-get update
- sudo apt-get install -y python python3-distutils-extra python3-setuptools python-dev anacron python3-dev python3-crontab python-crontab (>=1.8.1) python-coverage pep8 pyflakes python-apt python3-apt python-mock python3-mock lsb-release dh-systemd
- which python3
# travis is "funny" it has a non-distro python3 that will not find
# python modules installed via apt-get
script: (cd test ; PATH=/usr/bin:$PATH make)
