#!/bin/bash
#
# Copyright (C) 2016 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This file is part of le6-auto-upgrade
#
# le6-auto-upgrade is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

set -e

dir="/usr/share/help/pt_BR/le-help"
if [ ! -d  $dir ];then
    mkdir -p $dir
fi
if [ ! -L /usr/share/help/pt_BR/le-help/le-auto-upgrade.page.page ];then
    ln -s /usr/share/help-langpack/pt_BR/le-help/le-auto-upgrade.page /usr/share/help/pt_BR/le-help/le-auto-upgrade.page
fi

#DEBHELPER#
